export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_FEATURED_PRODUCTS = 'FETCH_FEATURED_PRODUCTS';
export const FETCH_CLASSES = 'FETCH_CLASSES';
export const FETCH_POPULAR_CLASSES = 'FETCH_POPULAR_CLASSES';
